fix(deps): fix Ledger hardware wallet support (#13048)
When using some Ledger Nano hardware wallets, some commands fail with:

    ERROR: finding ledger: LedgerHID device (idx 0) not found.
    Ledger LOCKED OR Other Program/Web Browser may have control of device.

Examples are `lotus wallet new secp256k1-ledger` and `lotus-shed ledger list`.

This issue was fixed upstream in https://github.com/Zondax/ledger-go/pull/40,
which then got pulled in https://github.com/Zondax/ledger-filecoin-go/pull/38,
which was released as https://github.com/Zondax/ledger-filecoin-go/releases/tag/v1.0.1.

So the fix is to simply update to `ledger-filecoin-go` v1.0.1, which is all
that this PR does.