fix === Errors cli/wallet.go:198: Errorf format % is missing verb at end of string cli/wallet.go:329: Printf call needs 1 arg but has 2 args cli/wallet.go:335: Printf call needs 1 arg but has 2 args cli/wallet.go:341: Printf call needs 1 arg but has 2 args cli/wallet.go:346: Printf call needs 1 arg but has 2 args cli/wallet.go:352: Printf call needs 1 arg but has 2 args cli/wallet.go:357: Printf call needs 1 arg but has 2 args cli/wallet.go:386: Printf call needs 1 arg but has 2 args