fix === Errors cli/services_send_test.go:57:3: cannot use mockApi (type *mocks.MockFullNode) as type api.FullNode in field value: 	*mocks.MockFullNode does not implement api.FullNode (missing WalletMsigImport method) markets/retrievaladapter/provider_test.go:183:5: cannot use mockFull (type *mocks.MockFullNode) as type api.FullNode in field value: 	*mocks.MockFullNode does not implement api.FullNode (missing WalletMsigImport method)